imports:
    - { resource: ../config.yml }
    - { resource: parameters.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/%kernel.environment%/routing.yml"
        strict_requirements: ~
